<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create($this->table(), function (Blueprint $table) {
            $table->id();

            // Generated by this package, not by Dialog — their send response
            // contains no identifier of any kind.
            $table->string('reference')->index();

            // Dialog's own campaign id, learned only when a delivery receipt
            // arrives. This is the id searchable in their portal. Named
            // distinctly from `campaign_id` below, which is ours.
            $table->string('dialog_campaign_id')->nullable()->index();

            $table->foreignId('campaign_id')->nullable()->constrained($this->campaignTable())->nullOnDelete();

            // For a bulk chunk this holds the full comma-separated list, which
            // is why it is a text column rather than a short string.
            $table->text('to');

            $table->text('message')->nullable();
            $table->string('sender_id')->nullable();
            $table->string('type', 20)->default('single');
            $table->string('message_type', 20)->default('transactional');
            $table->string('status', 20)->default('pending')->index();

            // Captured at send time so cost can be reconciled later even if
            // the message body is not retained.
            $table->string('encoding', 10)->nullable();
            $table->unsignedInteger('segments')->default(1);

            // The raw body Dialog returned, e.g. "1" or "2008". Kept verbatim
            // so an unrecognised code is still recoverable after the fact.
            $table->string('response_code', 20)->nullable();

            $table->text('error')->nullable();
            $table->nullableMorphs('notifiable');
            $table->json('metadata')->nullable();

            $table->timestamp('sent_at')->nullable();
            $table->timestamp('delivered_at')->nullable();
            $table->timestamp('failed_at')->nullable();
            $table->timestamps();

            $table->index(['status', 'created_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists($this->table());
    }

    private function table(): string
    {
        return (string) config('dialog-esms.logging.log_table', 'dialog_sms_logs');
    }

    private function campaignTable(): string
    {
        return (string) config('dialog-esms.logging.campaign_table', 'dialog_sms_campaigns');
    }
};
